<?php
/**
 * Basic PHP Web Page (index.php)
 * This file requires a PHP server environment (e.g., Apache with PHP, XAMPP, MAMP) to run.
 */

// 1. Define a variable for the page title
$pageTitle = "Key Tracker Dashboard";

date_default_timezone_set('America/New_York');

function getConnection() {
    $server = 'localhost';
    $user = 'cameron';
    $password = 'M@rtyRock$';
    $database = 'keytracker';

}

// 2. Get the current date and time using PHP's date() function
$currentDateTime = date("l, F j, Y - h:i:s A T");



// 3. Define a simple function to greet the user
function greetUser($name) {
    // htmlspecialchars is used to sanitize output, a good security practice
    return "Welcome back, " . htmlspecialchars($name) . "!";
}

$userName = "Residence life staff member";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- PHP used to set the dynamic page title -->
    <title><?php echo $pageTitle; ?></title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #e9eff5;
            color: #333;
            text-align: center;
        }
        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 30px;
            background-color: #fff;
            border-radius: 12px;
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #2c3e50;
            margin-bottom: 15px;
        }
        p {
            font-size: 1.1em;
            line-height: 1.6;
            color: #555;
        }
        .timestamp {
            margin-top: 30px;
            padding: 15px;
            background-color: #ecf0f1;
            border-radius: 8px;
            font-size: 0.9em;
            color: #7f8c8d;
        }
    </style>
</head>a
<body>
    <div class="container">
        <!-- Outputting the variable $pageTitle -->
        <h1><?php echo $pageTitle; ?></h1>

        <!-- Using the PHP function to generate content -->
        <p><strong><?php echo greetUser($userName); ?></strong></p>

        <p>If you would like to search for a student please fill in one or more of the following fields: </p>
        <br>
        <form action = "search.php" method = "post">
            Student Name: <input type="text" name="student_name">
            Student ID: <input type="text" name="student_id">
            <br>
            Room Number: <input type="text" name="room_number">
            <br>
            <input type="submit" value="Search">
        </form>

        <!-- Example of a conditional statement in PHP -->
        <?php
        $userRole = "admin"; // Change this to 'guest' or 'user' to see the change
        if ($userRole === "admin") {
            echo "<p style='color: #27ae60; font-weight: bold;'>Status: You have administrative privileges.</p>";
        } else {
            echo "<p style='color: #c0392b;'>Status: Standard access level.</p>";
        }
        ?>

        <!-- Outputting the dynamic date and time -->
        <div class="timestamp">
            This page was generated by the server on: <strong><?php echo $currentDateTime; ?></strong>
        </div>

    </div>
</body>
</html>
